const initialState = {
  pokemons: [
    {
      id: 1,
      name: "bulbasaur",
      hp: 45,
      attack: 49,
      defense: 49,
      speed: 45,
      height: 7,
      weight: 69,
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/1.svg",
      types: ["grass", "poison"],
      inDataBase: false,
    },
    {
      id: 2,
      name: "ivysaur",
      hp: 60,
      attack: 62,
      defense: 63,
      speed: 60,
      height: 10,
      weight: 130,
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/2.svg",
      types: ["grass", "poison"],
      inDataBase: false,
    },
    {
      id: 3,
      name: "venusaur",
      hp: 80,
      attack: 82,
      defense: 83,
      speed: 80,
      height: 20,
      weight: 1000,
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/3.svg",
      types: ["grass", "poison"],
      inDataBase: false,
    },
    {
      id: 4,
      name: "charmander",
      hp: 39,
      attack: 52,
      defense: 43,
      speed: 65,
      height: 6,
      weight: 85,
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/4.svg",
      types: ["fire"],
      inDataBase: false,
    },
    {
      id: 5,
      name: "charmeleon",
      hp: 58,
      attack: 64,
      defense: 58,
      speed: 80,
      height: 11,
      weight: 190,
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/5.svg",
      types: ["fire"],
      inDataBase: false,
    },
    {
      id: 6,
      name: "charizard",
      hp: 78,
      attack: 84,
      defense: 78,
      speed: 100,
      height: 17,
      weight: 905,
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/6.svg",
      types: ["fire", "flying"],
      inDataBase: false,
    },
    {
      id: 7,
      name: "squirtle",
      hp: 44,
      attack: 48,
      defense: 65,
      speed: 43,
      height: 5,
      weight: 90,
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/7.svg",
      types: ["water"],
      inDataBase: false,
    },
    {
      id: 8,
      name: "wartortle",
      hp: 59,
      attack: 63,
      defense: 80,
      speed: 58,
      height: 10,
      weight: 225,
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/8.svg",
      types: ["water"],
      inDataBase: false,
    },
    {
      id: 9,
      name: "blastoise",
      hp: 79,
      attack: 83,
      defense: 100,
      speed: 78,
      height: 16,
      weight: 855,
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/9.svg",
      types: ["water"],
      inDataBase: false,
    },
    {
      id: 10,
      name: "caterpie",
      hp: 45,
      attack: 30,
      defense: 35,
      speed: 45,
      height: 3,
      weight: 29,
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/10.svg",
      types: ["bug"],
      inDataBase: false,
    },
    {
      id: 11,
      name: "metapod",
      hp: 50,
      attack: 20,
      defense: 55,
      speed: 30,
      height: 7,
      weight: 99,
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/11.svg",
      types: ["bug"],
      inDataBase: false,
    },
    {
      id: 12,
      name: "butterfree",
      hp: 60,
      attack: 45,
      defense: 50,
      speed: 70,
      height: 11,
      weight: 320,
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/12.svg",
      types: ["bug", "flying"],
      inDataBase: false,
    },
    {
      id: 13,
      name: "weedle",
      hp: 40,
      attack: 35,
      defense: 30,
      speed: 50,
      height: 3,
      weight: 32,
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/13.svg",
      types: ["bug", "poison"],
      inDataBase: false,
    },
    {
      id: 14,
      name: "kakuna",
      hp: 45,
      attack: 25,
      defense: 50,
      speed: 35,
      height: 6,
      weight: 100,
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/14.svg",
      types: ["bug", "poison"],
      inDataBase: false,
    },
    {
      id: 15,
      name: "beedrill",
      hp: 65,
      attack: 90,
      defense: 40,
      speed: 75,
      height: 10,
      weight: 295,
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/15.svg",
      types: ["bug", "poison"],
      inDataBase: false,
    },
    {
      id: 16,
      name: "pidgey",
      hp: 40,
      attack: 45,
      defense: 40,
      speed: 56,
      height: 3,
      weight: 18,
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/16.svg",
      types: ["normal", "flying"],
      inDataBase: false,
    },
    {
      id: 17,
      name: "pidgeotto",
      hp: 63,
      attack: 60,
      defense: 55,
      speed: 71,
      height: 11,
      weight: 300,
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/17.svg",
      types: ["normal", "flying"],
      inDataBase: false,
    },
    {
      id: 18,
      name: "pidgeot",
      hp: 83,
      attack: 80,
      defense: 75,
      speed: 101,
      height: 15,
      weight: 395,
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/18.svg",
      types: ["normal", "flying"],
      inDataBase: false,
    },
    {
      id: 19,
      name: "rattata",
      hp: 30,
      attack: 56,
      defense: 35,
      speed: 72,
      height: 3,
      weight: 35,
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/19.svg",
      types: ["normal"],
      inDataBase: false,
    },
    {
      id: 20,
      name: "raticate",
      hp: 55,
      attack: 81,
      defense: 60,
      speed: 97,
      height: 7,
      weight: 185,
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/20.svg",
      types: ["normal"],
      inDataBase: false,
    },
    {
      id: 21,
      name: "spearow",
      hp: 40,
      attack: 60,
      defense: 30,
      speed: 70,
      height: 3,
      weight: 20,
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/21.svg",
      types: ["normal", "flying"],
      inDataBase: false,
    },
    {
      id: 22,
      name: "fearow",
      hp: 65,
      attack: 90,
      defense: 65,
      speed: 100,
      height: 12,
      weight: 380,
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/22.svg",
      types: ["normal", "flying"],
      inDataBase: false,
    },
    {
      id: 23,
      name: "ekans",
      hp: 35,
      attack: 60,
      defense: 44,
      speed: 55,
      height: 20,
      weight: 69,
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/23.svg",
      types: ["poison"],
      inDataBase: false,
    },
    {
      id: 24,
      name: "arbok",
      hp: 60,
      attack: 95,
      defense: 69,
      speed: 80,
      height: 35,
      weight: 650,
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/24.svg",
      types: ["poison"],
      inDataBase: false,
    },
    {
      id: 25,
      name: "pikachu",
      hp: 35,
      attack: 55,
      defense: 40,
      speed: 90,
      height: 4,
      weight: 60,
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/25.svg",
      types: ["electric"],
      inDataBase: false,
    },
    {
      id: 26,
      name: "raichu",
      hp: 60,
      attack: 90,
      defense: 55,
      speed: 110,
      height: 8,
      weight: 300,
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/26.svg",
      types: ["electric"],
      inDataBase: false,
    },
    {
      id: 27,
      name: "sandshrew",
      hp: 50,
      attack: 75,
      defense: 85,
      speed: 40,
      height: 6,
      weight: 120,
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/27.svg",
      types: ["ground"],
      inDataBase: false,
    },
    {
      id: 28,
      name: "sandslash",
      hp: 75,
      attack: 100,
      defense: 110,
      speed: 65,
      height: 10,
      weight: 295,
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/28.svg",
      types: ["ground"],
      inDataBase: false,
    },
    {
      id: 29,
      name: "nidoran-f",
      hp: 55,
      attack: 47,
      defense: 52,
      speed: 41,
      height: 4,
      weight: 70,
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/29.svg",
      types: ["poison"],
      inDataBase: false,
    },
    {
      id: 30,
      name: "nidorina",
      hp: 70,
      attack: 62,
      defense: 67,
      speed: 56,
      height: 8,
      weight: 200,
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/30.svg",
      types: ["poison"],
      inDataBase: false,
    },
    {
      id: 31,
      name: "nidoqueen",
      hp: 90,
      attack: 92,
      defense: 87,
      speed: 76,
      height: 13,
      weight: 600,
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/31.svg",
      types: ["poison", "ground"],
      inDataBase: false,
    },
    {
      id: 32,
      name: "nidoran-m",
      hp: 46,
      attack: 57,
      defense: 40,
      speed: 50,
      height: 5,
      weight: 90,
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/32.svg",
      types: ["poison"],
      inDataBase: false,
    },
    {
      id: 33,
      name: "nidorino",
      hp: 61,
      attack: 72,
      defense: 57,
      speed: 65,
      height: 9,
      weight: 195,
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/33.svg",
      types: ["poison"],
      inDataBase: false,
    },
    {
      id: 34,
      name: "nidoking",
      hp: 81,
      attack: 102,
      defense: 77,
      speed: 85,
      height: 14,
      weight: 620,
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/34.svg",
      types: ["poison", "ground"],
      inDataBase: false,
    },
    {
      id: 35,
      name: "clefairy",
      hp: 70,
      attack: 45,
      defense: 48,
      speed: 35,
      height: 6,
      weight: 75,
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/35.svg",
      types: ["fairy"],
      inDataBase: false,
    },
    {
      id: 36,
      name: "clefable",
      hp: 95,
      attack: 70,
      defense: 73,
      speed: 60,
      height: 13,
      weight: 400,
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/36.svg",
      types: ["fairy"],
      inDataBase: false,
    },
    {
      id: 37,
      name: "vulpix",
      hp: 38,
      attack: 41,
      defense: 40,
      speed: 65,
      height: 6,
      weight: 99,
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/37.svg",
      types: ["fire"],
      inDataBase: false,
    },
    {
      id: 38,
      name: "ninetales",
      hp: 73,
      attack: 76,
      defense: 75,
      speed: 100,
      height: 11,
      weight: 199,
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/38.svg",
      types: ["fire"],
      inDataBase: false,
    },
    {
      id: 39,
      name: "jigglypuff",
      hp: 115,
      attack: 45,
      defense: 20,
      speed: 20,
      height: 5,
      weight: 55,
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/39.svg",
      types: ["normal", "fairy"],
      inDataBase: false,
    },
    {
      id: 40,
      name: "wigglytuff",
      hp: 140,
      attack: 70,
      defense: 45,
      speed: 45,
      height: 10,
      weight: 120,
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/40.svg",
      types: ["normal", "fairy"],
      inDataBase: false,
    },
  ],
  types: [],
};

const rootReducer = (state = initialState, action) => {
  switch (action.type) {
    default:
      return { ...state };
  }
};

export default rootReducer;
